version: 1.0.{build}
image: Visual Studio 2019

branches:
  only:
    - /release-.*/
    - /dev-.*/

only_commits:
 files:
  - lib/ApiMultipartFormDataFormatter/
  - example/back-end/ApiBackEnd/

environment:
  global:
    AZURE_WEB_ACCOUNT_NAME:
      secure: 7a7dXUDl0K2pF+j2TcKMYM3EoBQA9CM0GAe3OIqevlc=

    AZURE_WEB_ACCOUNT_PASSWORD:
      secure: BMVUyCtkJ9EcXWjJxv1rSkUezXyEGE098lDnGlAAcx959P8zTSfhiT9WVb0o/1EX++h7FP1ZILge3Qun4t4klw==

    MY_GET_API_KEY:
      secure: 0HqMlO4KT03m1Obda0ta46zbO1EgtiSouotet2O7J7QU5SMEJfrv+GgM0cuNPL9l

    NUGET_API_KEY:
      secure: 7CpOZ0B3KsW3sFmCSb3XxHFpba52HEH5gGkb7g9NK93AkTkl339pjo6AkDsDUboa

configuration:
  - Debug
  - Release

build_script:
  # Restore nuget packages.
  - nuget restore "./lib/ApiMultipartFormDataFormatter/ApiMultiPartFormData.csproj"
  - dotnet restore "./lib/ApiMultipartFormDataFormatter/ApiMultiPartFormData.csproj"

  # Build demo page
  #- msbuild "./example/back-end/ApiBackEnd/ApiBackEnd.csproj" /p:DeployOnBuild=true /p:PublishProfile="Folder build"  /p:Configuration="Release"

  # Build library.
  - dotnet build "./lib/ApiMultipartFormDataFormatter/ApiMultiPartFormData.csproj" -c Release

# Run unit tests & integration tests.
test:
  assemblies:
    - '**\*.UnitTest.dll'
    - '**\*.UnitTests.dll'
    - '**\*.IntegrationTest.dll'

artifacts:
- path: ./example/back-end/ApiBackEnd/bin/Release/PublishOutput
  name: Azure deployment
  type: WebDeployPackage

- path: ./lib/ApiMultipartFormDataFormatter/bin/Debug/ApiMultipartFormDataFormatter.*.nupkg
  name: Nuget deployment
  type: WebDeployPackage

- path: ./lib/ApiMultipartFormDataFormatter/bin/Release/ApiMultipartFormDataFormatter.*.nupkg
  name: Myget deployment
  type: WebDeployPackage


deploy:
  # Demo website deployment.
- provider: WebDeploy
  server: https://apimultipartformdataservice.scm.azurewebsites.net:443/msdeploy.axd?site=ApiMultipartFormDataService
  website: ApiMultipartFormDataService
  username: $(AZURE_WEB_ACCOUNT_NAME)
  password: $(AZURE_WEB_ACCOUNT_PASSWORD)
  artifact: Azure deployment
  on:
    branch:
      - /dev-.*/

  # MyGet deployment.
- provider: NuGet
  server: https://www.myget.org/F/apimultipartformdataformatter
  api_key: $(MY_GET_API_KEY)
  skip_symbols: false
  artifact: Myget deployment
  on:
    branch:
      - /dev-.*/

  # Nuget deployment.
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  skip_symbols: false
  artifact: Nuget deployment
  on:
    branch:
      - /release-.*/
